name: DevSkim

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'resources/java-runtime**'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@v1
        with:
          ignore-globs: "dist/**/*,resources/java-runtime*/**/*,resources/web/common/js/jquery-ui/**/*,resources/web/panel/vendors/**/*,docs/common/**/*,docs/panel/**/*,docs/panel-stable/**/*,docs/javadoc/**/*,docs/javadoc-stable/**/*"

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: devskim-results.sarif
