name: Build JLink Binaries

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

env:
  image: localhost:5000/eclipse-temurin:21-jdk
  java-version: 21
  java-distribution: 'temurin'
  java-version-env: jdk-21.0.1+12
  source-prefix: https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1%2B12/OpenJDK21U-jdk_
  source-suffix: _hotspot_21.0.1_12

jobs:
  updatejlink:
    name: Update JLink Builds
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      matrix:
        include:
          - osname: Linux (GCC, amd64)
            folder: java-runtime-linux-amd64
            docker: false
            qemu: false
            os: ubuntu-latest
            script: jlink-jdk-linux.sh
          - osname: Linux (GCC, arm64)
            folder: java-runtime-linux-arm64
            docker: true
            qemu: true
            platform: linux/arm64
            build-image: true
            base: ubuntu:22.04
            dockerfile-os: linux
            source-arch-os: aarch64_linux
            source-ext: .tar.gz
            esum: e184dc29a6712c1f78754ab36fb48866583665fa345324f1a79e569c064f95e9
            os: ubuntu-latest
            script: jlink-jdk-docker.sh
            jdk: /opt/java/openjdk
          - osname: Windows (amd64)
            os: windows-latest
            folder: java-runtime-windows-amd64
            docker: false
            qemu: false
            script: jlink-jdk.bat
          - osname: macOS (amd64)
            folder: java-runtime-macos-amd64
            docker: false
            qemu: false
            os: macos-latest
            script: jlink-jdk-macos.sh
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up QEMU
      if: matrix.docker == true && matrix.qemu == true
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.platform }}
    - name: Build Image
      if: matrix.docker == true && matrix.build-image == true
      uses: docker/build-push-action@v5
      with:
        context: ./development-resources/docker-base-image-builder
        file: ./Dockerfile.${{ matrix.dockerfile-os }}
        platforms: ${{ matrix.platform }}
        push: true
        build-args: |
          BASE=${{ matrix.base }}
          ESUM=${{ matrix.esum }}
          JAVA-HOME=${{ matrix.jdk }}
          JAVA-VERSION=${{ env.java-version-env }}
          JRE=false
          SOURCE=${{ env.source-prefix }}${{ matrix.source-arch-os }}${{ env.source-suffix }}${{ matrix.source-ext }}
        tags: ${{ env.image }}
    - name: Set up JDK
      if: matrix.docker == false
      id: setup-java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.java-distribution }}
        java-version: ${{ env.java-version }}
        check-latest: true
    - name: Run JLink (Windows)
      if: startsWith(matrix.os, 'windows-') == true && matrix.docker == false
      env:
        FOLDER: ${{ matrix.folder }}
        SCRIPT: ${{ matrix.script }}
        JDK: ${{ steps.setup-java.outputs.path }}
      run: |
        cd development-resources
        cmd /C $env:SCRIPT
    - name: Run JLink (Non-Windows)
      if: startsWith(matrix.os, 'windows-') == false && matrix.docker == false
      env:
        FOLDER: ${{ matrix.folder }}
        SCRIPT: ${{ matrix.script }}
        JDK: ${{ steps.setup-java.outputs.path }}
      run: |
        cd development-resources
        chmod +x $SCRIPT
        /bin/bash $SCRIPT
    - name: Run JLink (Docker)
      if: matrix.docker == true
      env:
        FOLDER: ${{ matrix.folder }}
        SCRIPT: ${{ matrix.script }}
        JDK: ${{ matrix.jdk }}
        PLATFORM: ${{ matrix.platform }}
        IMAGE: ${{ env.image }}
      run: |
        cd development-resources
        chmod +x $SCRIPT
        /bin/bash $SCRIPT
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.folder }}
        path: resources/${{ matrix.folder }}/**
        if-no-files-found: error
        retention-days: 1
  commit:
    name: Commit Binaries
    runs-on: ubuntu-latest
    needs: updatejlink
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        path: resources
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        message: Updated the Java binaries
        default_author: github_actions